### ISSUE TITLE
Bug: unable to label batch 45

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#300]
<img width="364" alt="Image" src="https://github.com/user-attachments/assets/739107a0-a8b2-4a46-bbec-4ae8e03054a0" />

I can't tell what might be different about this batch that would make it unlabelable!

**Comment by maxachis** [comment]
In this case, it is because the batch itself has an `errored` status, which I was previously concealing. I should perhaps look into updating the query filters so that they properly filter on that and don't display them as available for labeling!

**Comment by maxachis** [comment]
Done! How does it look now?

**Comment by josh-chamberlain** [comment]
@maxachis acceptable—it still shows up in `All` so it'll be possible to figure out that there was an error if one goes missing. 

Do you know what the error was in this case? Looks like it grabbed the URLs to me.
